//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafýndan oluþturuldu.
//     Çalýþma Ransom Sürümü:4.0.30319.42000
//
//     Bu dosyada yapýlacak deðiþiklikler yanlýþ davranýþa neden olabilir ve
//     kod yeniden oluþturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaHarbor.Properties
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnglishResources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnglishResources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaHarbor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string AlreadyUpdatedText
        {
            get
            {
                return ResourceManager.GetString("alreadyupdatedText", resourceCulture);
            }
        }

        public static string DoFormatSelectionText
        {
            get
            {
                return ResourceManager.GetString("doformatselectionText", resourceCulture);
            }
        }

        public static string DownloadCompleteMessage
        {
            get
            {
                return ResourceManager.GetString("downloadCompleteMessage", resourceCulture);
            }
        }

        public static string DownloadCompleteText
        {
            get
            {
                return ResourceManager.GetString("downloadcompleteText", resourceCulture);
            }
        }

        public static string DownloadError
        {
            get
            {
                return ResourceManager.GetString("downloadError", resourceCulture);
            }
        }

        public static string DownloadLocationText
        {
            get
            {
                return ResourceManager.GetString("downloadLocationText", resourceCulture);
            }
        }

        public static string Downloads
        {
            get
            {
                return ResourceManager.GetString("downloads", resourceCulture);
            }
        }

        public static string DownloadText
        {
            get
            {
                return ResourceManager.GetString("downloadText", resourceCulture);
            }
        }

        public static string EnterAtLeastOne
        {
            get
            {
                return ResourceManager.GetString("enteratleastone", resourceCulture);
            }
        }

        public static string EnterSongPodcastUrl
        {
            get
            {
                return ResourceManager.GetString("entersongpodcasturl", resourceCulture);
            }
        }

        public static string EnterTextMessage
        {
            get
            {
                return ResourceManager.GetString("enterTextMessage", resourceCulture);
            }
        }

        public static string EnterYoutubeLinkText
        {
            get
            {
                return ResourceManager.GetString("enteryoutubelinkText", resourceCulture);
            }
        }

        public static string EpisodeNumber
        {
            get
            {
                return ResourceManager.GetString("episodenumber", resourceCulture);
            }
        }

        public static string Error
        {
            get
            {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }

        public static string FileNaming
        {
            get
            {
                return ResourceManager.GetString("fileNaming", resourceCulture);
            }
        }

        public static string FileNamingText
        {
            get
            {
                return ResourceManager.GetString("filenamingText", resourceCulture);
            }
        }

        public static string FolderNotFoundText
        {
            get
            {
                return ResourceManager.GetString("folderNotFoundText", resourceCulture);
            }
        }

        public static string HowManyText
        {
            get
            {
                return ResourceManager.GetString("howManyText", resourceCulture);
            }
        }

        public static string InputCorrectInt
        {
            get
            {
                return ResourceManager.GetString("inputcorrectint", resourceCulture);
            }
        }

        public static string MovieCompleted
        {
            get
            {
                return ResourceManager.GetString("moviecompleted", resourceCulture);
            }
        }

        public static string MovieName
        {
            get
            {
                return ResourceManager.GetString("moviename", resourceCulture);
            }
        }

        public static string MovieSeriesAudioFormat
        {
            get
            {
                return ResourceManager.GetString("movieseriesaudioformat", resourceCulture);
            }
        }

        public static string MovieSeriesKeyFormat
        {
            get
            {
                return ResourceManager.GetString("movieserieskeyformat", resourceCulture);
            }
        }

        public static string MovieSeriesVideoFormat
        {
            get
            {
                return ResourceManager.GetString("movieseriesvideoformat", resourceCulture);
            }
        }

        public static string MovieText
        {
            get
            {
                return ResourceManager.GetString("movieText", resourceCulture);
            }
        }

        public static string MovieYear
        {
            get
            {
                return ResourceManager.GetString("movieyear", resourceCulture);
            }
        }

        public static string MusicDownloadErrorText
        {
            get
            {
                return ResourceManager.GetString("musicDownloadErrorText", resourceCulture);
            }
        }

        public static string NoUpdate
        {
            get
            {
                return ResourceManager.GetString("noUpdate", resourceCulture);
            }
        }

        public static string OpenText
        {
            get
            {
                return ResourceManager.GetString("openText", resourceCulture);
            }
        }

        public static string PlaylistText
        {
            get
            {
                return ResourceManager.GetString("playlistText", resourceCulture);
            }
        }

        public static string PleaseCheckApp
        {
            get
            {
                return ResourceManager.GetString("pleasecheckapp", resourceCulture);
            }
        }

        public static string ProcessCompleteText
        {
            get
            {
                return ResourceManager.GetString("processCompleteText", resourceCulture);
            }
        }

        public static string RichTextBox1Text
        {
            get
            {
                return ResourceManager.GetString("richTextBox1.Text", resourceCulture);
            }
        }

        public static string SaveLocationText
        {
            get
            {
                return ResourceManager.GetString("saveLocationText", resourceCulture);
            }
        }

        public static string SelectDownloadLocationText
        {
            get
            {
                return ResourceManager.GetString("selectDownloadLocationText", resourceCulture);
            }
        }

        public static string SelectDownloadLocFirst
        {
            get
            {
                return ResourceManager.GetString("selectdownloadlocfirst", resourceCulture);
            }
        }

        public static string SelectFolderText
        {
            get
            {
                return ResourceManager.GetString("selectFolderText", resourceCulture);
            }
        }

        public static string SeriesName
        {
            get
            {
                return ResourceManager.GetString("seriesname", resourceCulture);
            }
        }

        public static string SeriesSeason
        {
            get
            {
                return ResourceManager.GetString("seriesseason", resourceCulture);
            }
        }

        public static string SeriesStartEp
        {
            get
            {
                return ResourceManager.GetString("seriesstartep", resourceCulture);
            }
        }

        public static string SeriesText
        {
            get
            {
                return ResourceManager.GetString("seriesText", resourceCulture);
            }
        }

        public static string ShutdownPCText
        {
            get
            {
                return ResourceManager.GetString("shutdownPCText", resourceCulture);
            }
        }

        public static string ShuttingDownText
        {
            get
            {
                return ResourceManager.GetString("shuttingdownText", resourceCulture);
            }
        }

        public static string Song
        {
            get
            {
                return ResourceManager.GetString("song", resourceCulture);
            }
        }

        public static string SongKey
        {
            get
            {
                return ResourceManager.GetString("songkey", resourceCulture);
            }
        }

        public static string SongUrl
        {
            get
            {
                return ResourceManager.GetString("songurl", resourceCulture);
            }
        }

        public static string StartText
        {
            get
            {
                return ResourceManager.GetString("startText", resourceCulture);
            }
        }

        public static string UpdateCompleted
        {
            get
            {
                return ResourceManager.GetString("updateCompleted", resourceCulture);
            }
        }

        public static string UpdateCompletedMessage
        {
            get
            {
                return ResourceManager.GetString("updateCompletedMessage", resourceCulture);
            }
        }

        public static string UpdateError
        {
            get
            {
                return ResourceManager.GetString("updateError", resourceCulture);
            }
        }

        public static string UpdatingPleaseWait
        {
            get
            {
                return ResourceManager.GetString("updatingPleaseWait", resourceCulture);
            }
        }

        public static string YtdlpAutoUpdateText
        {
            get
            {
                return ResourceManager.GetString("ytdlpAutoUpdateText", resourceCulture);
            }
        }

        public static string YtdlpUpdate
        {
            get
            {
                return ResourceManager.GetString("ytdlpUpdate", resourceCulture);
            }
        }
    }
}
