//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaHarbor.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaHarbor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   yt-dlp.exe Already Updated. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string alreadyupdatedText {
            get {
                return ResourceManager.GetString("alreadyupdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Theme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string appTheme {
            get {
                return ResourceManager.GetString("appTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy URL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string copyURL {
            get {
                return ResourceManager.GetString("copyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark Theme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string darkTheme {
            get {
                return ResourceManager.GetString("darkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Make Format Selection. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string doformatselectionText {
            get {
                return ResourceManager.GetString("doformatselectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download process completed successfully. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string downloadCompleteMessage {
            get {
                return ResourceManager.GetString("downloadCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Complete benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string downloadcompleteText {
            get {
                return ResourceManager.GetString("downloadcompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string downloadError {
            get {
                return ResourceManager.GetString("downloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Location: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string downloadLocationText {
            get {
                return ResourceManager.GetString("downloadLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloads benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string downloads {
            get {
                return ResourceManager.GetString("downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string downloadText {
            get {
                return ResourceManager.GetString("downloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter at least one value. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string enteratleastone {
            get {
                return ResourceManager.GetString("enteratleastone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the name of the song/podcast: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string entersongpodcasturl {
            get {
                return ResourceManager.GetString("entersongpodcasturl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the name of the song/podcast: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string enterTextMessage {
            get {
                return ResourceManager.GetString("enterTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a YouTube link. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string enteryoutubelinkText {
            get {
                return ResourceManager.GetString("enteryoutubelinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Episode Completed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string episodenumber {
            get {
                return ResourceManager.GetString("episodenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Naming benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fileNaming {
            get {
                return ResourceManager.GetString("fileNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Naming benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string filenamingText {
            get {
                return ResourceManager.GetString("filenamingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Folder Not Found. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string folderNotFoundText {
            get {
                return ResourceManager.GetString("folderNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How Many: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string howManyText {
            get {
                return ResourceManager.GetString("howManyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a valid number. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string inputcorrectint {
            get {
                return ResourceManager.GetString("inputcorrectint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Theme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string lightTheme {
            get {
                return ResourceManager.GetString("lightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie Completed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string moviecompleted {
            get {
                return ResourceManager.GetString("moviecompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie Name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string moviename {
            get {
                return ResourceManager.GetString("moviename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   . Episode/Movie Audio File Link: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string movieseriesaudioformat {
            get {
                return ResourceManager.GetString("movieseriesaudioformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   . Episode/Movie Key: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string movieserieskeyformat {
            get {
                return ResourceManager.GetString("movieserieskeyformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   . Episode/Movie Video File Link: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string movieseriesvideoformat {
            get {
                return ResourceManager.GetString("movieseriesvideoformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string movieText {
            get {
                return ResourceManager.GetString("movieText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Movie Year: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string movieyear {
            get {
                return ResourceManager.GetString("movieyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song download error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string musicDownloadErrorText {
            get {
                return ResourceManager.GetString("musicDownloadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Update benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string noUpdate {
            get {
                return ResourceManager.GetString("noUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string openText {
            get {
                return ResourceManager.GetString("openText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Playlist? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string playlistText {
            get {
                return ResourceManager.GetString("playlistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Check the Application. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pleasecheckapp {
            get {
                return ResourceManager.GetString("pleasecheckapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Completed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string processCompleteText {
            get {
                return ResourceManager.GetString("processCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MediaHarbor is a simple and user-friendly application used to download and organize media content from various platforms such as YouTube, Disney, and Spotify.
        ///
        ///1. Select Download Location:
        ///
        ///Click the &quot;Select Folder&quot; button to choose the folder where downloaded media files will be saved.
        ///Media Download:
        ///
        ///2. YouTube:
        ///
        ///Switch to the &quot;General&quot; tab to download YouTube videos.
        ///Paste the URL of the video or song into the &quot;YouTube URL&quot; field.
        ///Click the &quot;Download&quot; button to download the media.
        ///3. Disney: [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string richTextBox1_Text {
            get {
                return ResourceManager.GetString("richTextBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Location benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string saveLocationText {
            get {
                return ResourceManager.GetString("saveLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string searchText {
            get {
                return ResourceManager.GetString("searchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Select Download Location First! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selectDownloadLocationText {
            get {
                return ResourceManager.GetString("selectDownloadLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Select Download Location First! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selectdownloadlocfirst {
            get {
                return ResourceManager.GetString("selectdownloadlocfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Folder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selectFolderText {
            get {
                return ResourceManager.GetString("selectFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select an Quality First! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selectQuality {
            get {
                return ResourceManager.GetString("selectQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Series Name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string seriesname {
            get {
                return ResourceManager.GetString("seriesname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Season No: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string seriesseason {
            get {
                return ResourceManager.GetString("seriesseason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Episode: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string seriesstartep {
            get {
                return ResourceManager.GetString("seriesstartep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Series benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string seriesText {
            get {
                return ResourceManager.GetString("seriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shut Down Computer After Process? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string shutdownPCText {
            get {
                return ResourceManager.GetString("shutdownPCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shutting Down Computer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string shuttingdownText {
            get {
                return ResourceManager.GetString("shuttingdownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string song {
            get {
                return ResourceManager.GetString("song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song / Podcast Key benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string songkey {
            get {
                return ResourceManager.GetString("songkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song / Podcast URL: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string songurl {
            get {
                return ResourceManager.GetString("songurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string startText {
            get {
                return ResourceManager.GetString("startText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Completed benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string updateCompleted {
            get {
                return ResourceManager.GetString("updateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Completed. Now you can use the application. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string updateCompletedMessage {
            get {
                return ResourceManager.GetString("updateCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string updateError {
            get {
                return ResourceManager.GetString("updateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating, Please Wait! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string updatingPleaseWait {
            get {
                return ResourceManager.GetString("updatingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YouTube Search benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string youtubeSearch {
            get {
                return ResourceManager.GetString("youtubeSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Should yt-dlp update automatically? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ytdlpAutoUpdateText {
            get {
                return ResourceManager.GetString("ytdlpAutoUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yt-dlp.exe Update benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ytdlpUpdate {
            get {
                return ResourceManager.GetString("ytdlpUpdate", resourceCulture);
            }
        }
    }
}
